# -*- coding: utf-8 -*-
"""Tredence Analytics - Case Study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ffE8R_UI4EzcYb2F9GAxWVLiQ6M4DWZw
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np

# Select GPU if available, else CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# =========================================================
# 1. PRUNABLE LINEAR LAYER
# =========================================================
class PrunableLinear(nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()

        # Standard weight and bias (same as nn.Linear)
        self.weight = nn.Parameter(torch.randn(out_features, in_features) * 0.01)
        self.bias = nn.Parameter(torch.zeros(out_features))

        # Learnable gate scores (one per weight)
        # These will decide whether a weight is active or pruned
        self.gate_scores = nn.Parameter(torch.randn(out_features, in_features))

    def forward(self, x):
        # Convert gate_scores → values between 0 and 1
        gates = torch.sigmoid(self.gate_scores)

        # Multiply weights with gates → pruning happens here
        # If gate ≈ 0 → weight removed
        # If gate ≈ 1 → weight kept
        pruned_weight = self.weight * gates

        # Standard linear transformation
        return torch.matmul(x, pruned_weight.t()) + self.bias


# =========================================================
# 2. MODEL ARCHITECTURE
# =========================================================
class PrunableNet(nn.Module):
    def __init__(self):
        super().__init__()

        # Flatten CIFAR-10 image (3×32×32 → 3072)
        self.flatten = nn.Flatten()

        # Fully connected layers using prunable linear layers
        self.fc1 = PrunableLinear(32*32*3, 512)
        self.fc2 = PrunableLinear(512, 256)
        self.fc3 = PrunableLinear(256, 10)

        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.flatten(x)

        # Apply layers with ReLU activation
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))

        # Final output layer (no activation, logits)
        x = self.fc3(x)
        return x


# =========================================================
# 3. SPARSITY LOSS (L1 REGULARIZATION ON GATES)
# =========================================================
def compute_sparsity_loss(model):
    sparsity_loss = 0

    # Loop through all layers
    for module in model.modules():
        if isinstance(module, PrunableLinear):

            # Get gate values
            gates = torch.sigmoid(module.gate_scores)

            # L1 loss → encourages gates → 0 (pruning)
            sparsity_loss += torch.sum(gates)

    return sparsity_loss


# =========================================================
# 4. DATA LOADING (CIFAR-10)
# =========================================================
transform = transforms.Compose([
    transforms.ToTensor(),   # Convert image to tensor
])

# Training dataset
trainset = torchvision.datasets.CIFAR10(
    root='./data', train=True, download=True, transform=transform
)

# Test dataset
testset = torchvision.datasets.CIFAR10(
    root='./data', train=False, download=True, transform=transform
)

# DataLoaders for batching
trainloader = torch.utils.data.DataLoader(trainset, batch_size=128, shuffle=True)
testloader = torch.utils.data.DataLoader(testset, batch_size=128, shuffle=False)


# =========================================================
# 5. TRAINING FUNCTION
# =========================================================
def train_model(lambda_sparse):

    # Initialize model and move to device
    model = PrunableNet().to(device)

    # CrossEntropy for classification
    criterion = nn.CrossEntropyLoss()

    # Adam optimizer updates weights + gate_scores
    optimizer = optim.Adam(model.parameters(), lr=0.001)

    epochs = 22

    for epoch in range(epochs):
        model.train()
        total_loss = 0

        for inputs, labels in trainloader:
            inputs, labels = inputs.to(device), labels.to(device)

            optimizer.zero_grad()

            # Forward pass
            outputs = model(inputs)

            # Classification loss
            classification_loss = criterion(outputs, labels)

            # Sparsity loss (pruning pressure)
            sparsity_loss = compute_sparsity_loss(model)

            # Total loss = classification + sparsity penalty
            loss = classification_loss + lambda_sparse * sparsity_loss

            # Backpropagation
            loss.backward()
            optimizer.step()

            total_loss += loss.item()

        print(f"Epoch {epoch+1}, Loss: {total_loss:.4f}")

    return model


# =========================================================
# 6. MODEL EVALUATION
# =========================================================
def evaluate(model):
    model.eval()

    correct = 0
    total = 0

    # Disable gradient computation (faster inference)
    with torch.no_grad():
        for inputs, labels in testloader:
            inputs, labels = inputs.to(device), labels.to(device)

            outputs = model(inputs)

            # Get predicted class
            _, predicted = torch.max(outputs, 1)

            total += labels.size(0)
            correct += (predicted == labels).sum().item()

    # Accuracy %
    accuracy = 100 * correct / total
    return accuracy


# =========================================================
# 7. SPARSITY CALCULATION
# =========================================================
def calculate_sparsity(model, threshold=1e-2):
    total = 0
    pruned = 0

    for module in model.modules():
        if isinstance(module, PrunableLinear):

            # Get gate values
            gates = torch.sigmoid(module.gate_scores).detach().cpu().numpy()

            total += gates.size

            # Count how many gates are near zero
            pruned += np.sum(gates < threshold)

    # Return percentage of pruned weights
    return 100 * pruned / total


# =========================================================
# 8. GATE DISTRIBUTION PLOT
# =========================================================
def plot_gates(model):
    all_gates = []

    for module in model.modules():
        if isinstance(module, PrunableLinear):
            gates = torch.sigmoid(module.gate_scores).detach().cpu().numpy()
            all_gates.extend(gates.flatten())

    # Histogram of gate values
    plt.hist(all_gates, bins=50)
    plt.title("Gate Value Distribution")
    plt.xlabel("Gate Value")
    plt.ylabel("Frequency")
    plt.show()


# =========================================================
# 9. MAIN EXPERIMENT
# =========================================================
lambdas = [0.0001, 0.001, 0.01]

results = []

for lam in lambdas:
    print(f"\nTraining with lambda = {lam}")

    model = train_model(lam)

    acc = evaluate(model)
    sparsity = calculate_sparsity(model)

    results.append((lam, acc, sparsity))

    print(f"Lambda: {lam} | Accuracy: {acc:.2f}% | Sparsity: {sparsity:.2f}%")

    # Plot for mid lambda
    if lam == 0.001:
        plot_gates(model)


# =========================================================
# 10. RESULTS TABLE
# =========================================================
print("\nFinal Results:")
print("Lambda\tAccuracy\tSparsity")

for r in results:
    print(f"{r[0]}\t{r[1]:.2f}%\t\t{r[2]:.2f}%")